name: run-tests

on:
  # Run workflow manually
  workflow_dispatch:

  # PR for any branch
  pull_request:

  # push on any branch
  push:

defaults:
  run:
    shell: bash
    working-directory: src

jobs:
  test:
    uses: sbartholomeusz/gh-actions-common/.github/workflows/dotnet-test.yml@main
    with:
      dotnet_version: '7.0.x'
      path: './src/hello-world.sln'