name: run-tests

on:
  # Run workflow manually
  workflow_dispatch:

  # PR for any branch
  pull_request:

  # push on any branch
  push:

defaults:
  run:
    shell: bash
    working-directory: src

env:
  DOTNET_VERSION: '7.0.x'
  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_ACCOUNT_NAME: ${{ github.repository_owner }}

jobs:
  test:
    uses: sbartholomeusz/gh-actions-common/.github/workflows/test.yml@main
    with:
      dotnet_version: '6.x'
      path: './src/hello-world.sln'