name: run-tests

on:
  # Run workflow manually
  workflow_dispatch:

  # PR for any branch
  pull_request:

  # push on any branch
  push:

defaults:
  run:
    shell: bash
    working-directory: src

env:
  DOTNET_VERSION: '7.0.x'
  GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GH_ACCOUNT_NAME: ${{ github.repository_owner }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      
      - name: Build
        uses: sbartholomeusz/gh-actions-common/src/dotnet-build@main
        with:
          dotnet_version: '6.x'
          project_path: './src/hello-world.csproj'
          

      - name: Test
        uses: sbartholomeusz/gh-actions-common/src/dotnet-test@main
        with:
          dotnet_version: '6.x'