name: check-code-ql

on:
  # Run workflow manually
  workflow_dispatch:

  push:

  pull_request:

  # Staged PR's for any branch
  merge_group:

  # schedule:
  #   - cron: '18 17 * * 4'

defaults:
  run:
    shell: bash
    working-directory: ./src

jobs:   
  release:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: sbartholomeusz/gh-actions-common/.github/workflows/dotnet-code-ql.yml@main
    secrets: inherit
    with:
      dotnet_version: '7.0.x'
      path: './src'