name: create-release

on:
  # Run workflow manually
  workflow_dispatch:

  # Only run if prior workflow was successful
  workflow_run:
    workflows: ["run-tests"]
    branches: ["main"]
    types:
      - completed

defaults:
  run:
    shell: bash
    working-directory: src

jobs:   
  build:
    # Run only if prev workflow ran successfully
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    uses: sbartholomeusz/gh-actions-common/.github/workflows/dotnet-build.yml@main
    with:
      dotnet_version: '7.0.x'
      project_path: './src/hello-world.csproj'

  release:
    needs: build
    uses: sbartholomeusz/gh-actions-common/.github/workflows/dotnet-release.yml@main