name: create-release

on:
  # Run workflow manually
  workflow_dispatch:

defaults:
  run:
    shell: bash
    working-directory: src

jobs:   
  release:
    uses: sbartholomeusz/gh-actions-common/.github/workflows/dotnet-release.yml@feature/rework-sem-versioning
    secrets: inherit