name: Build, test and create a new app release

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: ./src

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 7.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Blazor WebAssembly app
        run: |
          dotnet build -c Release
          dotnet publish -c Release -o ./app_publish

      - name: Run Xunit tests
        run: dotnet test -c Release --no-build

      - name: Create package
        run: |
          mkdir package
          cp -r ./* ./package
          zip -r app_package.zip ./package
          mv app_package.zip ${{ github.workspace }}

  package:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Upload package
        uses: actions/upload-artifact@v2
        with:
          name: app_package
          path: ${{ github.workspace }}/app_package.zip
